# Generated by Django 3.0.7 on 2020-06-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('hkid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fisrstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
    ]
