# Generated by Django 3.0.7 on 2020-06-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkidapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fisrstname',
            new_name='firstname',
        ),
    ]
